### ISSUE TITLE
Validation of proxy model breaks OPNsense-devel on LAN-less OPNsense deployments

### ISSUE THREAD

**Issue by pv2b** [opnsense/core#1149]
Hi.

My dev box is currently set up with a single WAN interface. This is an unusual but not illegal configuration.

Ever since f3aed56978d9dc9a8526de3b02b9e2ab8354c380, which causes migrations to run on the proxy code, this breaks a make upgrade, with output like this:

```
file sizes/checksums  [1127]: 100%
packing files         [1127]: 100%
packing directories      [0]: 100%
Successfully built opnsense-devel-17.1.a_219.txz
Updating database digests format: 100%
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
        opnsense-devel-17.1.a_219

Number of packages to be removed: 1

The operation will free 21 MiB.
[1/1] Deinstalling opnsense-devel-17.1.a_219...
Resetting root shell
Updating /etc/shells
Updating /boot/loader.conf
Unhooking from /etc/rc
[1/1] Deleting files for opnsense-devel-17.1.a_219: 100%
Installing opnsense-devel-17.1.a_219...
Extracting opnsense-devel-17.1.a_219: 100%
Updating /etc/shells
Registering root shell
Hooking into /etc/rc
Updating /boot/loader.conf
Writing package version
Stopping configd...done
Starting configd.
Flush Phalcon volt templates
Execute model migrations
keep version OPNsense\CaptivePortal\CaptivePortal (0.0.0)
keep version OPNsense\Cron\Cron (0.0.0)
keep version OPNsense\Diagnostics\Netflow (0.0.0)
keep version OPNsense\IDS\IDS (0.0.0)

Fatal error: Uncaught exception 'Phalcon\Validation\Exception' with message '[forward.interfaces] please specify a valid interface
' in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:468
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(562): OPNsense\Base\BaseModel->serializeToConfig()
#1 /usr/local/opnsense/mvc/script/run_migrations.php(49): OPNsense\Base\BaseModel->runMigrations()
#2 {main}
  thrown in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php on line 468
Reloading GUI configuration
Message from opnsense-devel-17.1.a_219:
Thanks for all the fish...
Restarting webConfigurator...done.
root@OPNsense:~/core #
```

The forward.interfaces in the exception above refers to the proxy model.

In proxy.xml, forward.interface defaults to lan (source: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml#L168)

This is a problem on deployments that don't have a LAN interface, as this exception is then thrown.

**Comment by AdSchellevis** [comment]
@pv2b thanks for reporting, the issue is in the defaults, it should skip saving now.
