### ISSUE TITLE
Fix shutdown of configd

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#126]
When shutting down configd it logs an "error" :

OPNsense configd.py: Handler died on Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 96, in run     connection, client_address = sock.accept()   File "/usr/local/lib/python2.7/socket.py", line 202, in accept     sock, addr = self._sock.accept()   File "/usr/local/opnsense/service/modules/daemonize.py", line 53, in sigterm     sys.exit(0) SystemExit: 0

Which can be ignored, but should be surpressed if the daemon is in shutdown.

**Comment by AdSchellevis** [comment]
Fixed in https://github.com/opnsense/core/commit/79a01a60f4280e86d58e05a9aae87fac3faea65b
