### ISSUE TITLE
system health: division by zero and others

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#1421]
Not sure what the best fix is here, two spots are affected:

```
exception 'Exception' with message 'Error at /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php:148 - Division by zero (errno=2)' in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:84
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php(148): OPNsense\Base\ApiControllerBase->APIErrorHandler(2, 'Division by zer...', '/usr/local/opns...', 148, Array)
#1 /usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php(570): OPNsense\Diagnostics\Api\SystemhealthController->getSelection(Array, 'opensens', '0', 'opensens')
#2 [internal function]: OPNsense\Diagnostics\Api\SystemhealthController->getSystemHealthAction('wan-packets', 'opensens', '0', 'opensens', '0', 'opensens', '120', 'opensens', 'false', 'opensens', 'false')
#3 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\Diagnostics\Api\SystemhealthController), 'getSystemHealth...', Array)
#4 [internal function]: Phalcon\Dispatcher->_dispatch()
#5 [internal function]: Phalcon\Dispatcher->dispatch()
#6 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#7 {main}
```

Also I think these errors "Node no longer exists" are "new" in PHP 7.0....

```
PHP Warning:  OPNsense\Base\FieldTypes\InterfaceField::eventPostLoading(): Node no longer exists in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/InterfaceField.php on line 132
```

Interface race condition?
```
Phalcon\Validation\Exception: [OPNsense.IDS.IDS.general.interfaces] please specify a valid interface
 in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:503
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php(445): OPNsense\Base\BaseModel->serializeToConfig()
#1 [internal function]: OPNsense\IDS\Api\SettingsController->toggleRulesetAction('opnsense.test.r...', '1')
#2 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\IDS\Api\SettingsController), 'toggleRulesetAc...', Array)
#3 [internal function]: Phalcon\Dispatcher->_dispatch()
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#6 {main}
```

IPS

```
Exception: Error at /usr/local/opnsense/mvc/app/models/OPNsense/IDS/IDS.php:134 - array_key_exists(): The first argument should be either a string or an integer (errno=2) in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:84
Stack trace:
#0 [internal function]: OPNsense\Base\ApiControllerBase->APIErrorHandler(2, 'array_key_exist...', '/usr/local/opns...', 134, Array)
#1 /usr/local/opnsense/mvc/app/models/OPNsense/IDS/IDS.php(134): array_key_exists(4294967294, Array)
#2 /usr/local/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php(129): OPNsense\IDS\IDS->getRuleStatus(4294967294, 1)
#3 [internal function]: OPNsense\IDS\Api\SettingsController->searchInstalledRulesAction()
#4 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\IDS\Api\SettingsController), 'searchinstalled...', Array)
#5 [internal function]: Phalcon\Dispatcher->_dispatch()
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#8 {main}
```

**Comment by AdSchellevis** [comment]
`PHP Warning:  OPNsense\Base\FieldTypes\InterfaceField::eventPostLoading(): Node no longer exists in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/InterfaceField.php on line 132`


could be a damaged/invalid config, I definitely  can't reproduce it.

```
Phalcon\Validation\Exception: [OPNsense.IDS.IDS.general.interfaces] please specify a valid interface
 in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:503
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php(445): OPNsense\Base\BaseModel->serializeToConfig()
#1 [internal function]: OPNsense\IDS\Api\SettingsController->toggleRulesetAction('opnsense.test.r...', '1')
#2 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\IDS\Api\SettingsController), 'toggleRulesetAc...', Array)
#3 [internal function]: Phalcon\Dispatcher->_dispatch()
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#6 {main}
```

Can't reproduce either, even with invalid data in the interface it won't throw an error there, because it skips validation for unchanged fields (toggleRulesetAction doesn't change interface).


The last piece with array_exists is odd, it seems to crash on:
`array_key_exists(4294967294, Array)`
Which looks like valid input to me...

Close until we have a solid issue to track? Keep in mind that some people are experimenting with the sources and config at hand, which might lead to unexpected results.

**Comment by fichtner** [comment]
These are reappearing snippets, there are no one time crash reports here, but I'll follow your lead. :)

**Comment by AdSchellevis** [comment]
Ok, thanks, maybe someone points us in the right direction at some point, for now it's not really possible to solve (without adding type checks for situations which shouldn't really exist).
