### ISSUE TITLE
Could not send error report 

### ISSUE THREAD

**Issue by jwysen** [opnsense/core#1677]
after I press the send button, an empty page 
`Fatal error: Uncaught Error: Call to undefined function curl_file_create() in /usr/local/www/crash_reporter.php:42 Stack trace: #0 /usr/local/www/crash_reporter.php(115): upload_crash_report(Array, 'OPNsense/17.1.5') #1 {main} thrown in /usr/local/www/crash_reporter.php on line 42`

Additional Info's:
System Information
```
User-Agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QupZilla/2.0.2 Chrome/45.0.2454.101 Safari/537.36
FreeBSD 11.0-RELEASE-p8 #0 e84bb9532(stable/17.1): Sun Mar 26 15:30:53 CEST 2017     root@sensey32:/usr/obj/usr/src/sys/SMP
OPNsense 17.1.5-e27a303a3 [17.1.4-ea0bdd046] OpenSSL 1.0.2k  26 Jan 2017 (i386)
Time Sun, 11 Jun 2017 14:10:13 +0200
```
PHP Errors:
```
[11-Jun-2017 14:10:10 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function curl_file_create() in /usr/local/www/crash_reporter.php:42
Stack trace:
#0 /usr/local/www/crash_reporter.php(115): upload_crash_report(Array, 'OPNsense/17.1.5')
#1 {main}
  thrown in /usr/local/www/crash_reporter.php on line 42
```
/var/crash/PHP_errors.log:
```
[11-Jun-2017 14:02:38 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function curl_file_create() in /usr/local/www/crash_reporter.php:42
Stack trace:
#0 /usr/local/www/crash_reporter.php(115): upload_crash_report(Array, 'OPNsense/17.1.5')
#1 {main}
  thrown in /usr/local/www/crash_reporter.php on line 42
[11-Jun-2017 12:05:00 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/20151012/curl.so' - Shared object "libnghttp2.so.14" not found, required by "libcurl.so.4" in Unknown on line 0
```

**Comment by fichtner** [comment]
A mandatory package is missing. Can you update to 17.1.8 and try to reproduce?

**Comment by jwysen** [comment]
Thanks
I've got the error-message and waited with the update to reproduce and gather more infos if needed ;)
After your answer  I updated and I could send the error-report without this error-message. 

Thank you and have a nice weekend ...
