### ISSUE TITLE
MVC: Searching grid for non-existent name throws php error

### ISSUE THREAD

**Issue by fvanroie** [opnsense/core#2851]
**Problem Description**

Searching for Cron Jobs or Monit Services using the search filter in the gridview will throw a MVC php error when no items are found. For example searching for text _'sfdg'_ results in:

Cron Jobs
```
[26-Oct-2018 23:00:22 Etc/UTC] Exception: Error at /usr/local/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php:129 - Undefined index: cronPermissions (errno=8) in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:85
Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php(129): OPNsense\Base\ApiControllerBase->APIErrorHandler(8, 'Undefined index...', '/usr/local/opns...', 129, Array)
#1 /usr/local/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php(74): OPNsense\Base\UIModelGrid->fetch(Array, '7', '1', Array, false, 'sfdg')
#2 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php(242): OPNsense\Base\UIModelGrid->fetchBindRequest(Object(Phalcon\Http\Request), Array, 'description')
#3 /usr/local/opnsense/mvc/app/controllers/OPNsense/Cron/Api/SettingsController.php(164): OPNsense\Base\ApiMutableModelControllerBase->searchBase('jobs.job', Array, 'description')
#4 [internal function]: OPNsense\Cron\Api\SettingsController->searchJobsAction()
#5 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\Cron\Api\SettingsController), 'searchJobsActio...', Array)
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#8 {main}
```

Monit Services
```
[26-Oct-2018 23:27:44 Etc/UTC] Exception: Error at /usr/local/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php:129 - Undefined index: description (errno=8) in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:85
Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php(129): OPNsense\Base\ApiControllerBase->APIErrorHandler(8, 'Undefined index...', '/usr/local/opns...', 129, Array)
#1 /usr/local/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php(74): OPNsense\Base\UIModelGrid->fetch(Array, '7', '1', Array, false, 'blah')
#2 /usr/local/opnsense/mvc/app/controllers/OPNsense/Monit/Api/SettingsController.php(265): OPNsense\Base\UIModelGrid->fetchBindRequest(Object(Phalcon\Http\Request), Array)
#3 [internal function]: OPNsense\Monit\Api\SettingsController->searchAction('service')
#4 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\Monit\Api\SettingsController), 'searchAction', Array)
#5 [internal function]: Phalcon\Dispatcher->dispatch()
#6 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#7 {main}
```

**Conditions**

Step to reproduce the error:

Cron Jobs
- There is at least one cron job in the list
- The search text entered is _not_ be present in the list
- It happens in the GUI and in the API calling endpoint cron/settings/searchjobs

Monit Services
- There is at least one service in the list
- _Any_ search text is entered, it will always throw the error
- It happens in the GUI and in the API calling endpoint monit/settings/search/service

It seems so far that the **Crob Jobs** grid and **Monit Services** grid are both affected. It seems cronPermissions  and description aren't part of the respective models... I hope this description is enough to pinpoint the problem.

**Tested Versions**
> OPNsense 19.1.b_78-amd64
> FreeBSD 11.1-RELEASE-p15
> OpenSSL 1.0.2p  14 Aug 2018

and

> OPNsense 18.7.5_1-amd64
> FreeBSD 11.1-RELEASE-p14
> OpenSSL 1.0.2p  14 Aug 2018

**Comment by AdSchellevis** [comment]
@fvanroie thanks for the report, both should be fixed now with https://github.com/opnsense/core/commit/ee41c0fe255b16c5a2f72f226e90eaa96474538a  and https://github.com/opnsense/core/commit/bba9ef948f30ddebc9a447e34b3aaa8d235f6f49

**Comment by fichtner** [comment]
I'll add both to 18.7.7. :)

**Comment by fvanroie** [comment]
Great, thanks for the fast fix.
