### ISSUE TITLE
Static DHCP Mapping error

### ISSUE THREAD

**Issue by sachaz** [opnsense/core#2893]
I cannot add a static DHCP mapping.

Services: DHCPv4: Leases -> Add static mapping for existing address -> Set the IP out of the DHCP lease then:

```
Fatal error: Uncaught OPNsense\Core\ConfigException: no valid config loaded in /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php:240 Stack trace:
#0 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(182): OPNsense\Core\Config->checkvalid()
#1 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(221): OPNsense\Core\Config->fromArray(Array, Object(SimpleXMLElement), 'winsserver')
#2 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(221): OPNsense\Core\Config->fromArray(Array, Object(SimpleXMLElement), 2)
#3 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(221): OPNsense\Core\Config->fromArray(Array, Object(SimpleXMLElement), 'staticmap')
#4 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(221): OPNsense\Core\Config->fromArray(Array, Object(SimpleXMLElement), 'opt7')
#5 /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php(221): OPNsense\Core\Config->fromArray(Array, Object(SimpleXMLElement), 'dhcpd')
#6 /usr/local/etc/inc/config.inc(156): OPNsense\Core\ in /usr/local/opnsense/mvc/app/library/OPNsense/Core/Config.php on line 240 
```

**Comment by fichtner** [comment]
Which exact version is this?

**Comment by sachaz** [comment]
sorry for the noise it was la specif bug due to non freespace on disk

**Comment by fichtner** [comment]
Ok, no worries. Thanks for the feedback!
