### ISSUE TITLE
Unable to delete alias: An API exception occured

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#3037]
OPNsense 18.7.8

When trying to delete an alias, the following error message is shown:

> An API exception occured
> Error at /usr/local/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php:83 - Trying to get property of non-object (errno=8)

More details from `/tmp/PHP_errors.log`:

```
[11-Dec-2018 17:28:37 Europe/Berlin] Exception: Error at /usr/local/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php:83 - Trying to get property of non-object (errno=8) in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:85
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php(83): OPNsense\Base\ApiControllerBase->APIErrorHandler(8, 'Trying to get p...', '/usr/local/opns...', 83, Array)
#1 /usr/local/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php(111): OPNsense\Firewall\Alias->searchConfig('net_foo_bar7')
#2 /usr/local/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasController.php(130): OPNsense\Firewall\Alias->whereUsed('net_foo_bar7')
#3 [internal function]: OPNsense\Firewall\Api\AliasController->delItemAction('e3ea7ca6-29c7-4...')
#4 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(OPNsense\Firewall\Api\AliasController), 'delItemAction', Array)
#5 [internal function]: Phalcon\Dispatcher->dispatch()
#6 /usr/local/opnsense/www/api.php(26): Phalcon\Mvc\Application->handle()
#7 {main}
```

The alias in question has the following configuration:

```
          <alias uuid="e3ea7ca6-29c7-43ff-ae2e-da5fcebb8186">
            <enabled>1</enabled>
            <name>net_foo_bar7</name>
            <type>network</type>
            <proto/>
            <updatefreq/>
            <content>10.99.7.0/24</content>
            <description/>
          </alias>
```

**Comment by imidoriya** [comment]
I got this error also while trying to rename an alias.

**Comment by AdSchellevis** [comment]
@fraenki can you try https://github.com/opnsense/core/commit/54af1c434d274d00743fff0564e2e2f0fea7069d ?

**Comment by fraenki** [comment]
@AdSchellevis your patch fixes the issue, thanks!

**Comment by AdSchellevis** [comment]
@fraenki thanks for confirming!
