### ISSUE TITLE
configd: parameters seem to be mandatory in Pyhton 3.6 version

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#3271]
works ok:

    # configctl plugins configure dns stub

does not work:

    # configctl plugins configure dns

```
Mar  1 15:42:19 lej /configd.py: unable to sendback response [] for [plugins][configure][['dns']] {a199d8ac-6c35-4b0b-b4f7-44817a214c26}, message was Traceback (most recent call last):
File "/usr/local/opnsense/service/modules/processhandler.py", line 199, in run
result = self.action_handler.execute(exec_command, exec_action, exec_params, self.message_uuid)
File "/usr/local/opnsense/service/modules/processhandler.py", line 360, in execute
return '%s\n' % action_obj.execute(action_params, message_uuid)
File "/usr/local/opnsense/service/modules/processhandler.py", line 421, in execute
log_message = log_message + self.message % tuple(parameters[0:self.message.count('%s')])
TypeError: not enough arguments for format string
```

**Comment by AdSchellevis** [comment]
this doesn't appear to be related to python3, on 19.1.2 it's the same
```
Mar  3 17:42:47 OPNsense configd.py: unable to sendback response [] for [plugins][configure][['dns']] {873149b1-857f-4301-b07b-4dff1973fde3}, message was Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 199, in run     result = self.action_handler.execute(exec_command, exec_action, exec_params, self.message_uuid)   File "/usr/local/opnsense/service/modules/processhandler.py", line 360, in execute     return '%s\n' % action_obj.execute(action_params, message_uuid)   File "/usr/local/opnsense/service/modules/processhandler.py", line 421, in execute     log_message = log_message + self.message % tuple(parameters[0:self.message.count('%s')]) TypeError: not enough arguments for format string
```

**Comment by AdSchellevis** [comment]
I don't think this ever worked before:
https://github.com/opnsense/core/blob/a458aec929255250125aa8013b1e640da9fd8057/src/opnsense/service/conf/actions.d/actions_plugins.conf#L5

The message assumes a parameter, which isn't there....

**Comment by fichtner** [comment]
Interesting, I never noticed before. Thanks for the quick fix!
