### ISSUE TITLE
flowd_aggregate crash

### ISSUE THREAD

**Issue by DonConto** [opnsense/core#3715]
Netflow crashes after a minute or two. Not sure, but the problem occurs after adding an additional interface via "Interfaces: Assignments" for ovpns1. Maybe there is a 'corpse' in a config file now?!

Output:

root@OPNsense:~ # /usr/local/opnsense/scripts/netflow/flowd_aggregate.py --console
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 224, in <module>
    Main()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 136, in __init__
    self.run()
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 160, in run
    aggregate_flowd(self.config, do_vacuum)
  File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 68, in aggregate_flowd
    for flow_record in parse_flow(prev_recv, config.flowd_source):
  File "/usr/local/opnsense/scripts/netflow/lib/parse.py", line 74, in parse_flow
    for flow_record in FlowParser(filename, recv_stamp):
  File "/usr/local/opnsense/scripts/netflow/lib/flowparser.py", line 139, in __iter__
    data_fields=ntohl(header[3])
  File "/usr/local/opnsense/scripts/netflow/lib/flowparser.py", line 118, in _parse_binary
    raw_data[raw_data_idx:raw_data_idx + fsize]
struct.error: unpack requires a buffer of 8 bytes
root@OPNsense:~ #

I tried to reset and repair via GUI and also a rm of the sqlite files. But nothing helped.

**Comment by AdSchellevis** [comment]
@DonConto https://github.com/opnsense/core/commit/01d8fb296e69b99b271da0ec92caf7e1b572b953 should catch these errors.

To test, use the `opnsense-patch 01d8fb2` on a console (and restart the flowd_aggregate service).

**Comment by DonConto** [comment]
Netflow service is now stable. Thank you for your support.

**Comment by AdSchellevis** [comment]
@DonConto thanks for letting us know!

**Comment by NigelWhatling** [comment]
[This](https://github.com/opnsense/core/issues/3715#issuecomment-534170486) worked for me too. 👍
