### ISSUE TITLE
list_counters.py fails to run

### ISSUE THREAD

**Issue by Cubox-** [opnsense/core#3798]
Hi,

I am getting an error in my backend log:
```
configd.py: [92c93ac7-5027-43bd-8f0b-45d3d370b1d0] Script action failed with Command '/usr/local/opnsense/scripts/filter/list_counters.py 'json'' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 484, in execute stdout=output_stream, stderr=error_stream) File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/filter/list_counters.py 'json'' returned non-zero exit status 1.
```

```
<cubox@Thera.cubox>-<~> λ python3.7 /usr/local/opnsense/scripts/filter/list_counters.py 'json'
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/filter/list_counters.py", line 42, in <module>
    if line.find('[') == -1  and line[0] not in (' ', '\t'):
IndexError: string index out of range
```

Here is the output from the pfctl command:
```
all
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  18                
	In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
enc
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  0                 
	In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
enc0
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  0                 
	In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
lo
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  0                 
	In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
lo0
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  3                 
	In4/Pass:    [ Packets: 68348              Bytes: 12267189           ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 68264              Bytes: 12264222           ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 8949               Bytes: 3773451            ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
openvpn
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  0                 
	In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
ovpnc1
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  9                 
	In4/Pass:    [ Packets: 88049              Bytes: 2465372            ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 91425              Bytes: 3704290            ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 2987               Bytes: 1258157            ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
pflog
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  0                 
	In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
pflog0
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  0                 
	In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
pfsync
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  0                 
	In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
pfsync0 (skip)
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  0                 
	In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
re0
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  25                
	In4/Pass:    [ Packets: 2710782            Bytes: 822288839          ]
	In4/Block:   [ Packets: 8662               Bytes: 1503164            ]
	Out4/Pass:   [ Packets: 6137794            Bytes: 7419434356         ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 2298               Bytes: 651128             ]
	Out6/Pass:   [ Packets: 2988               Bytes: 1258217            ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
tun
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  0                 
	In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
tun1
	Cleared:     Wed Nov  6 02:29:41 2019
	References:  0                 
	In4/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In4/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out4/Block:  [ Packets: 0                  Bytes: 0                  ]
	In6/Pass:    [ Packets: 0                  Bytes: 0                  ]
	In6/Block:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Pass:   [ Packets: 0                  Bytes: 0                  ]
	Out6/Block:  [ Packets: 0                  Bytes: 0                  ]
```

I am running FreeBSD 12.1-RELEASE using the master branch from github.com/opnsense/src (commit b5d93c850).
OPNsense is running from the master branch from github.com/opnsense/core, commit https://github.com/opnsense/core/commit/8a83b3bb123c9f8a12a637693509a29f149699bf

I am aware that I'm running quite a "cutting edge" setup, but my box is set as FreeBSD running opnsense rather than the default opnsense using FreeBSD.

**Comment by fichtner** [comment]
Hi,

I'll mark this community support for the moment. src.git isn't ready and we don't have reference BETA build right now. The time frame for this is early December.


Cheers,
Franco

**Comment by AdSchellevis** [comment]
@Cubox- probably an extra empty line, https://github.com/opnsense/core/commit/196d46238336aec125a865b1e2dc78fc4570f1d3 should do the trick

**Comment by Cubox-** [comment]
> src.git isn't ready and we don't have a reference BETA build right now. The time frame for this is early December.

I'm happy to report that I have no issue using src.git in it's current state. While I am very much aware that this is not supported and at my own risk, thanks for the patch.
https://github.com/opnsense/core/commit/196d46238336aec125a865b1e2dc78fc4570f1d3 fixed the issue.

The upgrade to FreeBSD 12 was prompted to a bug I had which I thought would be fixed with FreeBSD 12, but was in fact an error in my make.conf.

Thanks for your help and for all the effort on OPNsense

**Comment by fichtner** [comment]
@Cubox- thanks for the feedback, I was only trying to level expectations. We're working on HBSD integration now and it looks good so the first packages can be built in a few days it seems. :)

Tagged this patch as a cleanup and will release it in 19.7.7 since it does no harm.


Cheers,
Franco
