### ISSUE TITLE
Dashboard: widget title and link wrong in 21.1.3

### ISSUE THREAD

**Issue by devNan0** [opnsense/core#4795]
**Describe the bug**
Instead of the correct title for each widget, $widget_name + "_title" will be displayed.
Example:
Instead of "Services" with link to `/status_services.php` we now have "services_status_title" with link to `/services_status_title_link`

This bug was introduced with 21.1.3 and has (AFAIK) to do with this commit: https://github.com/opnsense/core/commit/f67e242eaabb6db3ed98195586221bd0b054a0f0

![image](https://user-images.githubusercontent.com/49376203/110633006-89b8a380-81a8-11eb-9c82-bb1330723f3b.png)

**To Reproduce**

1. Go to 'Dashboard'

**Expected behavior**
![image](https://user-images.githubusercontent.com/49376203/110633515-211df680-81a9-11eb-9e72-7843ed790589.png)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.3 (amd64, OpenSSL 1.1.1j).
AMD GX-412TC SOC (4 cores)

**Comment by fichtner** [comment]
A little weird that this wasn’t caught in development. Are you sure reverting this commit works?

**Comment by AdSchellevis** [comment]
I'll take a look, missed this too to be honest.

**Comment by fichtner** [comment]
It looks legit, my bad. Though I wish we could avoid the use of $$

**Comment by AdSchellevis** [comment]
I'll leave a note in the code, go enjoy your off-time :)

**Comment by fichtner** [comment]
Or at least ${$foo} ?

**Comment by AdSchellevis** [comment]
```
opnsense-patch 45199e3
```

should fix the dashboard

**Comment by AdSchellevis** [comment]
@devNan0 thanks for reporting !

**Comment by devNan0** [comment]
Tested it and works fine.

Thanks for the fast fix @AdSchellevis

**Comment by lattera** [comment]
Would providing a hotpatch release (2.1.3.1) make sense?

**Comment by fichtner** [comment]
https://twitter.com/opnsense/status/1369654652162170880

**Comment by lattera** [comment]
Awesome! Thanks a bunch!

**Comment by Taomyn** [comment]
Since I applied this patch I now get

```
[547c6f90-d720-4689-bb8c-ceb9d01b0188] Script action failed with Command '/usr/local/opnsense/scripts/systemhealth/queryLog.py --limit '200' --offset '0' --filter '' --module 'core' --filename 'system'' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 479, in execute stdout=output_stream, stderr=error_stream) File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/systemhealth/queryLog.py --limit '200' --offset '0' --filter '' --module 'core' --filename 'system'' returned non-zero exit status 1.
```

And the General log will no longer display anything. I attempted to restart the all the services of the firewall and I was left with:

```
Enter an option: 11

Writing firmware setting...done.
Writing trust files...done.
Configuring login behaviour...done.
Configuring CRON...done.
Setting timezone...done.
Setting hostname: bart.star-one.co.uk
Generating /etc/hosts...done.
Generating /etc/resolv.conf...done.
Configuring loopback interface...done.
Creating wireless clone interfaces...done.
Configuring VLAN interfaces...done.
Configuring DMZ interface...done.
Configuring GUEST interface...done.
Configuring LAN interface...done.
Configuring WAN interface...done.
Creating IPsec VTI instances...done.
Creating OpenVPN instances...done.
Setting up routes...done.
Configuring firewall........done.
Starting PFLOG...done.
Starting DHCPv4 service...done.
Starting router advertisement service...done.
Starting NTP service...done.
Configuring OpenSSH...done.
Starting Unbound DNS...done.
Starting web GUI...done.
Syncing OpenVPN settings...

```
The original patch logged:
```
root@bart:~ # opnsense-patch 45199e3
Fetched 45199e3 via https://github.com/opnsense/core
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 45199e34526fb3012d0d7d1ca983f37dfb30bb47 Mon Sep 17 00:00:00 2001
|From: Ad Schellevis <ad@opnsense.org>
|Date: Wed, 10 Mar 2021 14:18:45 +0100
|Subject: [PATCH] Bugfix dashboard widget headers, partly revert and explain
| https://github.com/opnsense/core/commit/f67e242eaabb6db3ed98195586221bd0b054a0f0.
| closes https://github.com/opnsense/core/issues/4795
|
|---
| src/www/foot.inc  | 5 +++--
| src/www/index.php | 9 +++++----
| 2 files changed, 8 insertions(+), 6 deletions(-)
|
|diff --git a/src/www/foot.inc b/src/www/foot.inc
|index 0f6971e3a4..9c8834b992 100644
|--- a/src/www/foot.inc
|+++ b/src/www/foot.inc
--------------------------
Patching file www/foot.inc using Plan A...
Hunk #1 succeeded at 36.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/src/www/index.php b/src/www/index.php
|index dd6abb0241..5680dd8205 100644
|--- a/src/www/index.php
|+++ b/src/www/index.php
--------------------------
Patching file www/index.php using Plan A...
Hunk #1 succeeded at 380 (offset -3 lines).
done
All patches have been applied successfully.  Have a nice day.`
```
So I used the console to log in and perform a reboot which brought the firewall back to life but the General log is still broken.
