### ISSUE TITLE
flowd_aggregate died with message Traceback (...) KeyError: 'packets' 

### ISSUE THREAD

**Issue by ericschdt** [opnsense/core#4796]
**Important notices**
[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
[x] I have searched the existing issues and I'm convinced that mine is new.
[x] The title contains the plugin to which this issue belongs

**Describe the bug**
Seems to be a never ending story (https://github.com/opnsense/core/issues/4735, https://github.com/opnsense/core/issues/4751). :-)

I upgraded to the latest OPNSense and voilá:

```
2021-03-10T15:20:06 	flowd aggregate died with message Traceback (most recent call last): File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 160, in run aggregate_flowd(self.config, do_vacuum) File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 80, in aggregate_flowd stream_agg_object.add(copy.copy(flow_record)) File "/usr/local/opnsense/scripts/netflow/lib/aggregates/source.py", line 110, in add super(FlowSourceAddrDetails, self).add(flow) File "/usr/local/opnsense/scripts/netflow/lib/aggregates/__init__.py", line 183, in add flow['packets_consumed'] = consume_perc * flow['packets'] KeyError: 'packets'
2021-03-10T15:20:06 	flowparser failed to unpack flow_engine_info (unpack requires a buffer of 12 bytes)
2021-03-10T15:20:06 	flowparser failed to unpack as_info (unpack requires a buffer of 12 bytes)
2021-03-10T15:20:06 	flowparser failed to unpack flow_times (unpack requires a buffer of 8 bytes)
2021-03-10T15:20:06 	flowparser failed to unpack agent_info (unpack requires a buffer of 16 bytes)
2021-03-10T15:20:06 	flowparser failed to unpack if_indices (unpack requires a buffer of 8 bytes)
2021-03-10T15:20:06 	flowparser failed to unpack srcdst_port (unpack requires a buffer of 4 bytes)
```

Location of the error
https://github.com/opnsense/core/blob/de291e62660996b04d589381cad3396db5e9eb80/src/opnsense/scripts/netflow/lib/aggregates/__init__.py#L183

**Environment**
OPNsense 21.1.3-amd64
FreeBSD 12.1-RELEASE-p14-HBSD
OpenSSL 1.1.1j  16 Feb 2021

**Comment by AdSchellevis** [comment]
the problem is in the data flowd collects, for some reason it seems to be incomplete. But let's try to set defaults. You know you can always try patches upfront so you don't have to wait for our next release?

**Comment by AdSchellevis** [comment]
opnsense-patch  c0e4f8d

**Comment by ericschdt** [comment]
> opnsense-patch  c0e4f8d

That worked!
```
2021-03-10T16:25:32 | start watching flowd
2021-03-10T16:25:25 | startup, check database.
```

> Eventually I would love to ditch the netgraph+flowd construction, data records without packets do suggest there's something else wrong, but flowd (https://www.mindrot.org/projects/flowd/) is quite old and not very well maintained, the binary format underneath we had to reverse engineer to keep support on python 3

Sounds reasonable to me. Looking forward to a more robust and better maintainable solution!

**Comment by ericschdt** [comment]
Oh, it worked in the first place, but then `sqlite3.ProgrammingError: You did not supply a value for binding 7.`

```
2021-03-10T16:26:54 | flowd aggregate died with message Traceback (most recent  call last):   File  "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 160, in  run     aggregate_flowd(self.config, do_vacuum)   File  "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 80, in  aggregate_flowd     stream_agg_object.add(copy.copy(flow_record))   File  "/usr/local/opnsense/scripts/netflow/lib/aggregates/source.py", line  110, in add     super(FlowSourceAddrDetails, self).add(flow)   File  "/usr/local/opnsense/scripts/netflow/lib/aggregates/__init__.py", line  185, in add     self._update_cur.execute(self._update_stmt, flow)  sqlite3.ProgrammingError: You did not supply a value for binding 7.
-- | --
2021-03-10T16:26:54 | flowparser failed to unpack flow_engine_info (unpack requires a buffer of 12 bytes)
2021-03-10T16:26:54 | flowparser failed to unpack as_info (unpack requires a buffer of 12 bytes)
[...]
```

**Comment by AdSchellevis** [comment]
it really looks like mangled data, maybe some crash in between. 

can you add https://github.com/opnsense/core/commit/edd9b6c433b25c5033c603b9acb4d2f0ce0d29d3 on top (just leave the other patch and run the next command)?
```
opnsense-patch edd9b6c
```

**Comment by ericschdt** [comment]
> opnsense-patch edd9b6c

Seems to run for the moment. If it crashes again, I will report again. Thanks.

**Comment by AdSchellevis** [comment]
thanks, I'll close for now, just ping if it needs to be reopened.

**Comment by ericschdt** [comment]
As a follow up: It hasn't crashed yet, but my log is now full of
```
2021-03-10T16:46:33 | flowparser failed to unpack flow_engine_info (unpack requires a buffer of 12 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack flow_engine_info (unpack requires a buffer of 12 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack flow_engine_info (unpack requires a buffer of 12 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack as_info (unpack requires a buffer of 12 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack flow_times (unpack requires a buffer of 8 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack agent_info (unpack requires a buffer of 16 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack if_indices (unpack requires a buffer of 8 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack tag (unpack requires a buffer of 4 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack recv_time (unpack requires a buffer of 8 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack tag (unpack requires a buffer of 4 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack flow_engine_info (unpack requires a buffer of 12 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack as_info (unpack requires a buffer of 12 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack flow_engine_info (unpack requires a buffer of 12 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack as_info (unpack requires a buffer of 12 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack flow_times (unpack requires a buffer of 8 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack agent_info (unpack requires a buffer of 16 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack if_indices (unpack requires a buffer of 8 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack tag (unpack requires a buffer of 4 bytes)
2021-03-10T16:46:33 | flowparser failed to unpack proto_flags_tos (unpack requires a buffer of 4 bytes)
[...]
```
