### ISSUE TITLE
flowd_aggregate not start

### ISSUE THREAD

**Issue by stich86** [opnsense/core#4877]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

After a reboot (OPNSense running on VMWare), the flowd_aggregate doesn't start

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

**Describe alternatives you considered**

**Screenshots**

**Relevant log files**

2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowd aggregate died with message Traceback (most recent call last): File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 160, in run aggregate_flowd(self.config, do_vacuum) File "/usr/local/opnsense/scripts/netflow/flowd_aggregate.py", line 80, in aggregate_flowd stream_agg_object.add(copy.copy(flow_record)) File "/usr/local/opnsense/scripts/netflow/lib/aggregates/source.py", line 112, in add src_addr = flow['dst_addr'] KeyError: 'dst_addr' |  
-- | -- | -- | --
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack if_indices (unpack requires a buffer of 8 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack octets (unpack requires a buffer of 8 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack packets (unpack requires a buffer of 8 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack recv_time (unpack requires a buffer of 8 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack tag (unpack requires a buffer of 4 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack recv_time (unpack requires a buffer of 8 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack tag (unpack requires a buffer of 4 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack proto_flags_tos (unpack requires a buffer of 4 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack recv_time (unpack requires a buffer of 8 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack tag (unpack requires a buffer of 4 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack flow_engine_info (unpack requires a buffer of 12 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack proto_flags_tos (unpack requires a buffer of 4 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack recv_time (unpack requires a buffer of 8 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack flow_times (unpack requires a buffer of 8 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack octets (unpack requires a buffer of 8 bytes) |  
2021-03-29T11:57:18 | /flowd_aggregate.py[44785] | flowparser failed to unpack flow_times (unpack requires a buffer of 8 bytes) |  
2021-03-29T11:57:15 | /flowd_aggregate.py[44785] | start watching flowd |  
2021-03-29T11:57:15 | /flowd_aggregate.py[44785] | startup, check database.

**Additional context**

**Environment**

Running on VMWare:

OPNsense 21.1.3_3-amd64
FreeBSD 12.1-RELEASE-p14-HBSD
OpenSSL 1.1.1j 16 Feb 2021
--

**Comment by fichtner** [comment]
Same as https://github.com/opnsense/plugins/issues/2305  Disk corruption, nothing we can do here.

**Comment by stich86** [comment]
Ok for disk corruption, I've recreate the database flow from setting
