### ISSUE TITLE
Memory leak/crash when opening IPSec logs after clearing them

### ISSUE THREAD

**Issue by lfuelling** [opnsense/core#4997]
## Version Info
OPNsense 21.1.5-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

I have not used the IPSec functionality on other versions so I can't state the last working version.

## Issue Description

I was viewing the IPSec logs to troubleshoot something and decided to delete the current log. 
Clicking the delete button did "nothing" visible so I clicked it multiple times and then refreshed the page.
After that the firewall webui became unresponsive needing ~28 seconds for the TCP connection establishment (according to devtools) alone.

The CPU usage is constantly >80% and RAM and SWAP are fully allocated.

## Log output

I found the following log entries which seem to be related.

### Backend Log

```
2021-05-19T01:02:57 | configd.py[91251] | [670a1e54-c1b2-4492-acce-05ff6444505f] request pfctl byte/packet counters | &nbsp;
2021-05-19T01:02:57 | configd.py[91251] | unable to sendback response [Execute error ] for [system][diag][['log', '20', '0', '', 'core', 'ipsec']] {b21bfba1-179c-4c97-ad4f-61d043fdfbff}, message was Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 202, in run self.connection.sendall(('%s\n' % result).encode()) BrokenPipeError: [Errno 32] Broken pipe | &nbsp;
2021-05-19T01:02:57 | configd.py[91251] | [some-redacted-uuid] Script action failed with Command '/usr/local/opnsense/scripts/systemhealth/queryLog.py --limit '20' --offset '0' --filter '' --module 'core' --filename 'ipsec'' died with &lt;Signals.SIGKILL: 9&gt;. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 479, in execute stdout=output_stream, stderr=error_stream) File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/systemhealth/queryLog.py --limit '20' --offset '0' --filter '' --module 'core' --filename 'ipsec'' died with &lt;Signals.SIGKILL: 9&gt;.
```

### General Log

All 8137 "General Log" Entries beside the `was killed: out of swap space` one were `swap_pager_getswapspace` back to `2021-05-19T00:59:30`. 

```
2021-05-19T01:02:55 | kernel | swap_pager_getswapspace(20): failed | &nbsp;
2021-05-19T01:02:55 | kernel | swap_pager_getswapspace(22): failed | &nbsp;
2021-05-19T01:02:55 | kernel | swap_pager_getswapspace(25): failed | &nbsp;
2021-05-19T01:02:55 | kernel | swap_pager_getswapspace(28): failed | &nbsp;
2021-05-19T01:02:55 | kernel | swap_pager_getswapspace(32): failed | &nbsp;
2021-05-19T01:02:55 | kernel | swap_pager_getswapspace(8): failed | &nbsp;
2021-05-19T01:02:55 | kernel | swap_pager_getswapspace(16): failed | &nbsp;
2021-05-19T01:02:55 | kernel | swap_pager_getswapspace(32): failed | &nbsp;
2021-05-19T01:02:54 | kernel | pid 57243 (python3.7), jid 0, uid 0, was killed: out of swap space | &nbsp;
2021-05-19T01:02:54 | kernel | swap_pager_getswapspace(18): failed | &nbsp;
2021-05-19T01:02:54 | kernel | swap_pager_getswapspace(20): failed
``` 

## Processes

In `System > Diagnostics > Activity` I still can see three processes seeming to be busy collecting the log entries:

```
86310 | root | 102 | 0 | 3059 | 1180 | CPU3 | 3 | 18:57 | 100.00% | /usr/local/bin/python3 /usr/local/opnsense/scripts/systemhealth/queryLog.py --limit 20 --offset 0 --filter --module core --filename ipsec (python3.7)
&nbsp; | 86357 | root | 103 | 0 | 3049 | 1190 | CPU1 | 1 | 17:20 | 100.00% | /usr/local/bin/python3 /usr/local/opnsense/scripts/systemhealth/queryLog.py --limit 20 --offset 0 --filter --module core --filename ipsec (python3.7)
&nbsp; | 11564 | root | 102 | 0 | 476 | 425 | CPU0 | 0 | 20:37 | 99.37% | /usr/local/bin/python3 /usr/local/opnsense/scripts/systemhealth/queryLog.py --limit 20 --offset 0 --filter --module core --filename ipsec (python3.7)
```

Killing these processes fixes the issue but opening the IPSec log again creates a new one of those processes that runs even when the browser is closed which again is using up all the resources and has to be killed manually (or by waiting for all the memory to run out).

**Comment by lfuelling** [comment]
Wow, that is one useless bot...
