### ISSUE TITLE
Crash Reporter notification every time dashboard is refreshed after update to v22.7.7

### ISSUE THREAD

**Issue by dohlin** [opnsense/core#6118]
Weird one here, but after upgrading to v22.7.7 (and v22.7.7_1) every single time I refresh the dashboard page I get the red notification light in the corner and a message saying crash detected.  I can dismiss the notification and crash, go back to the dashboard, and hit refresh and it'll pop right back up again instantly.

System Information:
```
User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
FreeBSD 13.1-RELEASE-p3 stable/22.7-n250262-83840459d88 SMP amd64
OPNsense 22.7.7_1 391f1de80
Plugins os-cache-1.0_1 os-crowdsec-1.0.1 os-dnscrypt-proxy-1.12_1 os-dyndns-1.27_3 os-etpro-telemetry-1.6_1 os-hw-probe-1.0_1 os-intrusion-detection-content-pt-open-1.0_1 os-intrusion-detection-content-snort-vrt-1.1_1 os-iperf-1.0_1 os-ntopng-1.2_2 os-nut-1.8.1_1 os-redis-1.1_2 os-telegraf-1.12.6 os-theme-cicada-1.29 os-theme-vicuna-1.41 os-upnp-1.4_2 os-wireguard-1.13 
Time Fri, 04 Nov 2022 09:19:37 -0500
OpenSSL 1.1.1s  1 Nov 2022
Python 3.9.15
PHP 8.0.25
```

PHP Errors:
```
[04-Nov-2022 09:17:47 America/Chicago] TypeError: array_merge(): Argument #1 must be of type array, null given in /usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/GeneralController.php:93
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/GeneralController.php(93): array_merge(NULL, Array)
#1 [internal function]: OPNsense\Wireguard\Api\GeneralController->getStatusAction()
#2 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\Wireguard\Api\GeneralController), 'getStatusAction', Array)
#3 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#4 /usr/local/opnsense/www/api.php(24): Phalcon\Mvc\Application->handle('/api/wireguard/...')
#5 {main}
```

I've tried reinstalling the wireguard plugin since the error seems to mention that, but no luck.  I've also tried searching and so far haven't come across any other reports of this problem.  Anything else I can try?  Thank you!

**Comment by fichtner** [comment]
PR exists in plugins.

**Comment by fichtner** [comment]
Sorry I was on mobile earlier. Link here https://github.com/opnsense/plugins/pull/3180

**Comment by dohlin** [comment]
> Sorry I was on mobile earlier. Link here [opnsense/plugins#3180](https://github.com/opnsense/plugins/pull/3180)

Awesome, thank you!!
