### ISSUE TITLE
Unbound (development): python logger causes a core dump on restart

### ISSUE THREAD

**Issue by swhite2** [opnsense/core#6191]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

A clear and concise description of what the bug is, including last known working version (if any).

(On development) Restarting Unbound causes the `logger.py` process to `pid xxxx (python3.9), jid 0, uid 0: exited on signal 6 (core dumped)`. When run separately with `--foreground` or modified to not use the Daemonizer at all, the program is properly closed on a `SIGTERM` (https://github.com/opnsense/core/blob/master/src/etc/inc/plugins.inc.d/unbound.inc#L115).

The bug seems related to the daemonization process, but we can't be sure until we further analyze the core dump. Other daemonized processes function correctly, but most use Unix domain sockets for communication. The logger hooks into the `kqueue` kernel notification mechanism.

**To Reproduce**

1. Restart Unbound in the GUI
2. run `dmesg`
3. Observe python core dump of previous process

Please note that this has no effect on functional behaviour, everything is working as it should and there are no zombie processes. The only leftover is an overwritten coredump in `/`.

**Expected behavior**

For the python process to not produce a core dump

**Describe alternatives you considered**

None

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1 development (amd64, OpenSSL).

**Comment by swhite2** [comment]
For reference, after enabling python debug symbols the stack trace is as follows:

```
#0  0x000000080097213a in thr_kill () from /lib/libc.so.7
#1  0x00000008008f1764 in raise () from /lib/libc.so.7
#2  0x0000000800996d89 in abort () from /lib/libc.so.7
#3  0x00000008046438a1 in std::__1::thread::~thread() () from /usr/lib/libc++.so.1
#4  0x000000080869f8c9 in ?? () from /usr/local/lib/python3.9/site-packages/duckdb.cpython-39.so
#5  0x000000080869d5d0 in duckdb::TaskScheduler::~TaskScheduler() ()
   from /usr/local/lib/python3.9/site-packages/duckdb.cpython-39.so
#6  0x00000008085a4a0f in duckdb::DatabaseInstance::~DatabaseInstance() ()
   from /usr/local/lib/python3.9/site-packages/duckdb.cpython-39.so
#7  0x00000008085f70b1 in std::__1::__shared_ptr_emplace<duckdb::DuckDB, std::__1::allocator<duckdb::DuckDB> >::__on_zero_shared() () from /usr/local/lib/python3.9/site-packages/duckdb.cpython-39.so
#8  0x000000080888821d in duckdb::DuckDBPyConnection::~DuckDBPyConnection() ()
   from /usr/local/lib/python3.9/site-packages/duckdb.cpython-39.so
#9  0x00000008088827c0 in duckdb::DuckDBPyConnection::Cleanup() ()
   from /usr/local/lib/python3.9/site-packages/duckdb.cpython-39.so
#10 0x000000080045d4f1 in capsule_dealloc (o=<PyCapsule at remote 0x806072e50>) at Objects/capsule.c:261
#11 0x00000008004d6a66 in _Py_Dealloc (op=<PyCapsule at remote 0x806072e50>) at Objects/object.c:2209
#12 0x00000008004b0b7f in _Py_DECREF (filename=0x8002a9506 "./Include/object.h", lineno=497,
    op=<PyCapsule at remote 0x806072e50>) at ./Include/object.h:430
#13 0x00000008004b451c in _Py_XDECREF (op=<PyCapsule at remote 0x806072e50>) at ./Include/object.h:497
#14 0x00000008004ba9d1 in free_keys_object (keys=0x80566ca20) at Objects/dictobject.c:598
#15 0x00000008004b2997 in dictkeys_decref (dk=0x80566ca20) at Objects/dictobject.c:333
#16 0x00000008004b6bb8 in dict_dealloc (mp=0x8060676b0) at Objects/dictobject.c:2026
#17 0x00000008004d6a66 in _Py_Dealloc (
    op={'__name__': 'duckdb', '__doc__': <unknown at remote 0x806033d30>, '__package__': <unknown at remote 0x80604f7c0>, '__loader__': None, '__spec__': None, 'DuckDBPyRelation': <pybind11_type(__init__=<wrapper_descriptor at remote 0x80605acb0>, __doc__=None, __module__='duckdb', __pybind11_module_local_v4_clang_libcpp_cxxabi1002__=<PyCapsule at remote 0x80604fa40>, type=<property at remote 0x80605b050>, columns=<property at remote 0x80605b1d0>, types=<property at remote 0x80605b350>, dtypes=<property at remote 0x80605b4d0>, __len__=<instancemethod at remote 0x806048b50>, shape=<property at remote 0x80605b7d0>, filter=<instancemethod at remote 0x806048d10>, project=<instancemethod at remote 0x806048ad0>, set_alias=<instancemethod at remote 0x806048d50>, alias=<property at remote 0x80605bd10>, order=<instancemethod at remote 0x806048a90>, aggregate=<instancemethod at remote 0x806048c50>, sum=<instancemethod at remote 0x806048dd0>, count=<instancemethod at remote 0x806048e10>, median=<instancemethod at remote 0x8060...(truncated)) at Objects/object.c:2209
#18 0x000000080066136f in _Py_DECREF (filename=0x8002b88ee "Python/pystate.c", lineno=771,
    op={'__name__': 'duckdb', '__doc__': <unknown at remote 0x806033d30>, '__package__': <unknown at remote 0x80604f7c0>, '__loader__': None, '__spec__': None, 'DuckDBPyRelation': <pybind11_type(__init__=<wrapper_descriptor at remote 0x80605acb0>, __doc__=None, __module__='duckdb', __pybind11_module_local_v4_clang_libcpp_cxxabi1002__=<PyCapsule at remote 0x80604fa40>, type=<property at remote 0x80605b050>, columns=<property at remote 0x80605b1d0>, types=<property at remote 0x80605b350>, dtypes=<property at remote 0x80605b4d0>, __len__=<instancemethod at remote 0x806048b50>, shape=<property at remote 0x80605b7d0>, filter=<instancemethod at remote 0x806048d10>, project=<instancemethod at remote 0x806048ad0>, set_alias=<instancemethod at remote 0x806048d50>, alias=<property at remote 0x80605bd10>, order=<instancemethod at remote 0x806048a90>, aggregate=<instancemethod at remote 0x806048c50>, sum=<instancemethod at remote 0x806048dd0>, count=<instancemethod at remote 0x806048e10>, median=<instancemethod at remote 0x8060...(truncated)) at ./Include/object.h:430
#19 0x00000008006628ee in _PyInterpreterState_ClearModules (interp=0x801068010) at Python/pystate.c:771
#20 0x0000000800638c54 in _PyImport_Cleanup (tstate=0x801052010) at Python/import.c:626
#21 0x000000080065b8a5 in Py_FinalizeEx () at Python/pylifecycle.c:1426
#22 0x0000000800697b5b in Py_RunMain () at Modules/main.c:679
#23 0x0000000800697f9b in pymain_main (args=0x7fffffffeb58) at Modules/main.c:707
#24 0x0000000800698015 in Py_BytesMain (argc=2, argv=0x7fffffffec00) at Modules/main.c:731
#25 0x0000000000201942 in main (argc=2, argv=0x7fffffffec00) at ./Programs/python.c:15
```

The current workaround will be to use `/usr/bin/nohup /usr/local/opnsense/scripts/unbound/logger.py &` instead of daemonizing the process.

**Comment by swhite2** [comment]
Issue addressed with https://github.com/opnsense/core/commit/0474d2558f502a78f1ed57fd458d3d5421973e64, leaving it open until further notice.

**Comment by fichtner** [comment]
daemon use works as intended
