### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError

### ISSUE THREAD

**Issue by a1ad** [opnsense/core#6319]
After update from 22.7 > 23.1 tons of error messages like:

```
[10-Feb-2023 16:36:43 Europe/Brussels] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:8
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 8
```

**Comment by AdSchellevis** [comment]
`/usr/local/etc/inc/xmlrpc/hass.inc` isn't one of our files as far as I know.

**Comment by a1ad** [comment]
Looks like the "os-homeassistant-maxit plugin". Error is gone after I removed the plugin. Thanks for pointing me in the right direction.
