### ISSUE TITLE
IDS, Policy management UI broken ? 

### ISSUE THREAD

**Issue by yaourt** [opnsense/core#6322]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In the web UI, IDS policy management is returning the following php error:
`/usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:654: It's not possible to assign a complex type to properties, array given `

This is happening on a fresh install, up-to-date 23_1_6 with the etpro_telemetry installed and configured (valid token).

It was first observed on latest 22 version, but the system has been reinstalled from scratch since then. 

**To Reproduce**

1. Go to 'Services/IDS/Policy' (web UI)
2. Click on '+ (Add)'
3. Enabled: ticked / Priority: 0
4. Rulesets: tick one or more ET telemetry ruleset
5. Action: Alert
6. Rules: field cannot be edited (is this expected ?!?) 
7. New Action: Alert
8. Description: whatever description
9. Click on 'Save'
10. See error: `/usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:654: It's not possible to assign a complex type to properties, array given `

**Expected behavior**

The policy should be added

**Describe alternatives you considered**

This was happening on a system that have been updated to latest v22 and then re-installed with v23 from scratch.

**Screenshots**

Policy:
![image](https://user-images.githubusercontent.com/128949/218305181-b7271af8-85d7-4e4b-b420-63fdb1b3446e.png)

Error on save:
![image](https://user-images.githubusercontent.com/128949/218305206-fa596965-cfc0-45ae-91db-a1b6ea682164.png)

**Relevant log files**
System information:
```
User-Agent Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
FreeBSD 13.1-RELEASE-p5 stable/23.1-n250372-c4ad069e50a SMP amd64
OPNsense 23.1_6 6621e1999
Plugins os-etpro-telemetry-1.6_1 
Time Sun, 12 Feb 2023 10:17:03 +0000
OpenSSL 1.1.1s  1 Nov 2022
Python 3.9.16
PHP 8.1.14
```
PHP error
```
[12-Feb-2023 08:58:48 Etc/UTC] TypeError: It's not possible to assign a complex type to properties, array given in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:654
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#1 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#2 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#3 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#4 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(505): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#5 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(524): OPNsense\Base\BaseModel->toXML()
#6 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(587): OPNsense\Base\BaseModel->internalSerializeToConfig()
#7 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php(256): OPNsense\Base\BaseModel->serializeToConfig()
#8 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php(393): OPNsense\Base\ApiMutableModelControllerBase->save()
#9 /usr/local/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php(656): OPNsense\Base\ApiMutableModelControllerBase->addBase('policy', 'policies.policy')
#10 [internal function]: OPNsense\IDS\Api\SettingsController->addPolicyAction()
#11 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\IDS\Api\SettingsController), 'addPolicyAction', Array)
#12 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#13 /usr/local/opnsense/www/api.php(24): Phalcon\Mvc\Application->handle('/api/ids/settin...')
#14 {main}
[12-Feb-2023 08:59:07 Etc/UTC] TypeError: It's not possible to assign a complex type to properties, array given in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:654
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#1 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#2 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#3 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#4 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(505): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#5 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(524): OPNsense\Base\BaseModel->toXML()
#6 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(587): OPNsense\Base\BaseModel->internalSerializeToConfig()
#7 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php(256): OPNsense\Base\BaseModel->serializeToConfig()
#8 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php(393): OPNsense\Base\ApiMutableModelControllerBase->save()
#9 /usr/local/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php(656): OPNsense\Base\ApiMutableModelControllerBase->addBase('policy', 'policies.policy')
#10 [internal function]: OPNsense\IDS\Api\SettingsController->addPolicyAction()
#11 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\IDS\Api\SettingsController), 'addPolicyAction', Array)
#12 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#13 /usr/local/opnsense/www/api.php(24): Phalcon\Mvc\Application->handle('/api/ids/settin...')
#14 {main}
[12-Feb-2023 10:02:52 Etc/UTC] TypeError: It's not possible to assign a complex type to properties, array given in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:654
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#1 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#2 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#3 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#4 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(505): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#5 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(524): OPNsense\Base\BaseModel->toXML()
#6 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(587): OPNsense\Base\BaseModel->internalSerializeToConfig()
#7 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php(256): OPNsense\Base\BaseModel->serializeToConfig()
#8 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php(393): OPNsense\Base\ApiMutableModelControllerBase->save()
#9 /usr/local/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php(656): OPNsense\Base\ApiMutableModelControllerBase->addBase('policy', 'policies.policy')
#10 [internal function]: OPNsense\IDS\Api\SettingsController->addPolicyAction()
#11 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\IDS\Api\SettingsController), 'addPolicyAction', Array)
#12 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#13 /usr/local/opnsense/www/api.php(24): Phalcon\Mvc\Application->handle('/api/ids/settin...')
#14 {main}
[12-Feb-2023 10:16:29 Etc/UTC] TypeError: It's not possible to assign a complex type to properties, array given in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php:654
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#1 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#2 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#3 /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php(670): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#4 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(505): OPNsense\Base\FieldTypes\BaseField->addToXMLNode(Object(SimpleXMLElement))
#5 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(524): OPNsense\Base\BaseModel->toXML()
#6 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(587): OPNsense\Base\BaseModel->internalSerializeToConfig()
#7 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php(256): OPNsense\Base\BaseModel->serializeToConfig()
#8 /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php(393): OPNsense\Base\ApiMutableModelControllerBase->save()
#9 /usr/local/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php(656): OPNsense\Base\ApiMutableModelControllerBase->addBase('policy', 'policies.policy')
#10 [internal function]: OPNsense\IDS\Api\SettingsController->addPolicyAction()
#11 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\IDS\Api\SettingsController), 'addPolicyAction', Array)
#12 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#13 /usr/local/opnsense/www/api.php(24): Phalcon\Mvc\Application->handle('/api/ids/settin...')
#14 {main}
```

**Additional context**

N/A

**Environment**
N/A

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/991f27ee94726129a4250e093f1e9ed754a985ca should solve this, apparently the response type is wrong when there's no rule metadata (only the ET rules collect metadata as far as I know).

**Comment by yaourt** [comment]
:+1:  raised and fixed in 2 hours on a Sunday, you are awesome !
