### ISSUE TITLE
Reporting Unbound DNS not working anymore since OPNsense 23.1.5_2

### ISSUE THREAD

**Issue by Karo7** [opnsense/core#6456]
Date | Severity | Process | Line |  
-- | -- | -- | -- | --
2023-03-29T23:25:39 | Error | unbound | duckdb.ConversionException: Conversion Error: Could not convert string 'None' to INT32 |  
2023-03-29T23:25:39 | Error | unbound | db.connection.append('query', pandas.DataFrame(self.buffer)) |  
2023-03-29T23:25:39 | Error | unbound | File "/usr/local/opnsense/scripts/unbound/logger.py", line 167, in _read |  
2023-03-29T23:25:39 | Error | unbound | if not callback(key.fileobj, mask): |  
2023-03-29T23:25:39 | Error | unbound | File "/usr/local/opnsense/scripts/unbound/logger.py", line 216, in run_logger |  
2023-03-29T23:25:39 | Error | unbound | r.run_logger() |  
2023-03-29T23:25:39 | Error | unbound | File "/usr/local/opnsense/scripts/unbound/logger.py", line 223, in run |  
2023-03-29T23:25:39 | Error | unbound | run(inputargs.pipe, inputargs.flush_interval) |  
2023-03-29T23:25:39 | Error | unbound | File "/usr/local/opnsense/scripts/unbound/logger.py", line 239, in <module> |  
2023-03-29T23:25:39 | Error | unbound | Traceback (most recent call last):

[Date](javascript:void(0);)
[Severity](javascript:void(0);)
[Process](javascript:void(0);)
[Line](javascript:void(0);)
2023-03-29T23:25:39	Error	unbound	duckdb.ConversionException: Conversion Error: Could not convert string 'None' to INT32	
2023-03-29T23:25:39	Error	unbound	db.connection.append('query', pandas.DataFrame(self.buffer))	
2023-03-29T23:25:39	Error	unbound	File "/usr/local/opnsense/scripts/unbound/logger.py", line 167, in _read	
2023-03-29T23:25:39	Error	unbound	if not callback(key.fileobj, mask):	
2023-03-29T23:25:39	Error	unbound	File "/usr/local/opnsense/scripts/unbound/logger.py", line 216, in run_logger	
2023-03-29T23:25:39	Error	unbound	r.run_logger()	
2023-03-29T23:25:39	Error	unbound	File "/usr/local/opnsense/scripts/unbound/logger.py", line 223, in run	
2023-03-29T23:25:39	Error	unbound	run(inputargs.pipe, inputargs.flush_interval)	
2023-03-29T23:25:39	Error	unbound	File "/usr/local/opnsense/scripts/unbound/logger.py", line 239, in <module>	
2023-03-29T23:25:39	Error	unbound	Traceback (most recent call last):

**Comment by fichtner** [comment]
Also reported here https://www.reddit.com/r/opnsense/comments/125mecq/comment/je6zdkq/?context=3

**Comment by anjanms** [comment]
Thought I'd chime in to add additional information since I ran into this myself.

This is occurring for DNS queries that originate from Unbound itself rather than a network client. The logged query not having a network address or family throws off the fields inserted into the SQLite db. Such as when prefetch or serve-expired is enabled.

I've added the following to `/usr/local/opnsense/scripts/unbound/logger.py` just before `db.connection.append('query', pandas.DataFrame(self.buffer))`
```python
with open('/tmp/asdf.txt', 'w') as outfile:
    outfile.write(pandas.DataFrame(self.buffer).to_string())
```
Which produced this output prior to exiting with the error reported above
```
0  6160f903-7bf0-4214-a9b3-f2dfbe10790f  1680129782               A  obihai.telephony.goog.  0                       0  None  0   148  3  300  None  None
1  5fa80bfc-d9f1-455c-b466-cb716f4b60bc  1680129783  172.20.128.118                     ip4  A           pool.ntp.org.     0  0  None  0  147     3   300
2  d98d46f6-06b5-4c27-8454-d7705e93a5f4  1680129793    172.20.1.104                     ip4  A  jnn-pa.googleapis.com.     0  0  None  0   20     3   300
```

As a temporary fix for myself I added this to `Logger.log_entry()` within `/usr/local/opnsense/service/templates/OPNsense/Unbound/core/dnsbl_module.py`
```python
if query._client == '' and query._family == '':
    query._client = '127.127.127.127'
    query._family = 'ip4'
```

In the previous version these same queries simply presented with an address of `None` in the UI. Complete with attempted PTR lookups.

**Comment by AdSchellevis** [comment]
@anjanms  @Karo7  I need someone to test https://github.com/opnsense/core/commit/0a6a3a7715932b7fbb129b7fc62a4a8bf2a012d1, I couldn't reproduce the issue on my end, but the None values could be problematic in various scenario's.

```
opnsense-patch 0a6a3a7
```

**Comment by pbksol** [comment]
Unfortunately not. it's sill failing. See attached log. Patch was applied around 16:10
[resolver.log](https://github.com/opnsense/core/files/11112566/resolver.log)

**Comment by AdSchellevis** [comment]
@pbksol did you restart unbound after the patch, it sounds rather odd that there's still a "None" in there as these are now converted to empty strings. 

https://github.com/opnsense/core/blob/0a6a3a7715932b7fbb129b7fc62a4a8bf2a012d1/src/opnsense/service/templates/OPNsense/Unbound/core/dnsbl_module.py#L225

An extra check on the contents of the logger file (`/usr/local/opnsense/service/templates/OPNsense/Unbound/core/dnsbl_module.py`) would be much appreciated.

**Comment by pbksol** [comment]
@AdSchellevis yeah… Did not… Restartet unbound. I'll tell you in about 5 minutes what happens, that's the rough timeframe when it started failing.

**Comment by pbksol** [comment]
@AdSchellevis so… Sorry for the confusion – completely forgot to restart.

**The patch works**. Unbound is running 10 minutes, reporting is still filled with data, the last log file entry is from when it started, nothing else.

**Comment by Karo7** [comment]
thx everyone works for me

**Comment by anjanms** [comment]
The patch is all good here. Thanks!

**Comment by juanzelli** [comment]
The patch worked for me too. Many thanks.

**Comment by zimmermann-dev** [comment]
Patch did not work for me. Unbound runs for like 1 day max.

**Comment by zimmermann-dev** [comment]
Still same errors, can I fully remove unbound and clean reinstall it? 

Date | Severity | Process | Line
-- | -- | -- | --
2023-04-15T05:18:47 | Error | unbound | duckdb.ConversionException: Conversion Error: Could not convert string 'None' to INT32 (File "/usr/local/opnsense/scripts/unbound/logger.py", line 167, in _read)
2023-04-15T05:18:47 | Error | unbound | db.connection.append('query', pandas.DataFrame(self.buffer)) (File "/usr/local/opnsense/scripts/unbound/logger.py", line 216, in run_logger)
2023-04-15T05:18:47 | Error | unbound | if not callback(key.fileobj, mask): (File "/usr/local/opnsense/scripts/unbound/logger.py", line 223, in run)
2023-04-15T05:18:47 | Error | unbound | run(inputargs.pipe, inputargs.flush_interval) (File "/usr/local/opnsense/scripts/unbound/logger.py", line 239, in <module>)
2023-04-15T05:18:47 | Error | unbound | File "/usr/local/opnsense/scripts/unbound/logger.py", line 167, in _read
2023-04-15T05:18:47 | Error | unbound | File "/usr/local/opnsense/scripts/unbound/logger.py", line 216, in run_logger
2023-04-15T05:18:47 | Error | unbound | File "/usr/local/opnsense/scripts/unbound/logger.py", line 223, in run
2023-04-15T05:18:47 | Error | unbound | Traceback (most recent call last): (File "/usr/local/opnsense/scripts/unbound/logger.py", line 239, in <module>)

**Comment by zimmermann-dev** [comment]
Today it doesn't work again but I also get no new error messages.
