### ISSUE TITLE
DHCPv6 Leases --> No Dynamic leases + Log Error

### ISSUE THREAD

**Issue by dMopp** [opnsense/core#6891]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

DHCPv6 Leases --> No Dynamic leases + Log Error

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to Services/DHCPv6/Leases
2. See error

**Expected behavior**

I would like to see all v6 leases there.

**Describe alternatives you considered**

n.a.

**Screenshots**

n.a.

**Relevant log files**

```
2023-09-28T16:51:26+02:00 OPNsense.lan.dmopp.de configd.py[243]: [55fc67b9-0ccd-4fe3-844d-15ab86d90979] request ndp table
2023-09-28T16:51:26+02:00 OPNsense.lan.dmopp.de configd.py[243]: [296c27da-4ea1-437e-b22c-4c8cc88ae023] list dhcpv6 leases 1
2023-09-28T16:51:26+02:00 OPNsense.lan.dmopp.de configd.py[243]: [3caacedd-b14e-4ba2-a688-1d69395999dc] Request DHCPd6 status
2023-09-28T16:51:26+02:00 OPNsense.lan.dmopp.de configd.py[243]: [296c27da-4ea1-437e-b22c-4c8cc88ae023] Script action failed with Command '/usr/local/opnsense/scripts/dhcp/get_leases6.py --inactive '1'' returned non-zero exit status 1. at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/actions/script_output.py", line 44, in execute     subprocess.check_call(script_command, env=self.config_environment, shell=True,   File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call     raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/dhcp/get_leases6.py --inactive '1'' returned non-zero exit status 1.
2023-09-28T16:51:26+02:00 OPNsense.lan.dmopp.de configd.py[243]: [ddf63c65-0d45-4de3-afbf-13bcf669e49d] IPsec list legacy VirtualTunnelInterfaces
2023-09-28T16:51:26+02:00 OPNsense.lan.dmopp.de configd.py[243]: [ec32b225-5bd4-496c-939e-c0c1415fecb6] list dhcpv6 static mappings 0
2023-09-28T16:51:26+02:00 OPNsense.lan.dmopp.de configd.py[243]: [15009977-249b-42a0-a0f5-519badb0bd73] list dhcpv6 leases 1
2023-09-28T16:51:26+02:00 OPNsense.lan.dmopp.de configd.py[243]: [15009977-249b-42a0-a0f5-519badb0bd73] Script action failed with Command '/usr/local/opnsense/scripts/dhcp/get_leases6.py --inactive '1'' returned non-zero exit status 1. at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/actions/script_output.py", line 44, in execute     subprocess.check_call(script_command, env=self.config_environment, shell=True,   File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call     raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/usr/local/opnsense/scripts/dhcp/get_leases6.py --inactive '1'' returned non-zero exit status 1.
2023-09-28T16:51:26+02:00 OPNsense.lan.dmopp.de configd.py[243]: [c4af95a4-a2cb-4a63-b225-1ed2ca673f89] request mac table
2023-09-28T16:51:26+02:00 OPNsense.lan.dmopp.de configd.py[243]: [bb5c9f3c-c2b7-4dba-aa7b-f2d5c8a37465] request ifconfig
2023-09-28T16:51:27+02:00 OPNsense.lan.dmopp.de configd.py[243]: [d15979b6-f8a1-498c-b391-c3e37f8daaa8] system status
```

**Additional context**

n.a.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.5-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w 11 Sep 2023
Running in Proxmox VM

**Comment by AdSchellevis** [comment]
can you run the following on the console and return the output?

```
/usr/local/opnsense/scripts/dhcp/get_leases6.py --inactive '1'
```

**Comment by dMopp** [comment]
```
root@OPNsense:~ # /usr/local/opnsense/scripts/dhcp/get_leases6.py --inactive '1'
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/dhcp/get_leases6.py", line 161, in <module>
    parsed_lease = parse_lease(cur_lease)
  File "/usr/local/opnsense/scripts/dhcp/get_leases6.py", line 128, in parse_lease
    (segment_type, segment) = parse_iaaddr_iaprefix(cur_segment)
  File "/usr/local/opnsense/scripts/dhcp/get_leases6.py", line 62, in parse_iaaddr_iaprefix
    field_value = parse_date(parts[2], parts[3])
IndexError: list index out of range
```

**Comment by AdSchellevis** [comment]
@dMopp can you try https://github.com/opnsense/core/commit/a91bc81aafc200cddcf5f3194fcc9f736d16b487 ?

**Comment by dMopp** [comment]
Yes sure, how can I test it? :)

**Comment by AdSchellevis** [comment]
@dMopp thanks for confirming
