### ISSUE TITLE
OPNsense\Base\BaseModel->runMigrations() failed -  Option not in list when "lan" interface is missing

### ISSUE THREAD

**Issue by doktornotor** [opnsense/core#7077]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Ok, I'm back with another issue that probably no-one else hits. 🤣  Found on a box which does not have "lan" (I mean the identifier) interface.

`OPNsense\Base\BaseModel->runMigrations()` fails with _Option not in list.{lan}_ error when the "lan" interface is missing from configuration. See logs below. 

**To Reproduce**

1. Remove assignment of the interface with `lan` identifier from your firewall.
2. Install a plugin which uses lan as default interface, e.g. `os-mdns-repeater`
3. See error

**Expected behavior**

No errors.

**Relevant log files**

```
<147>1 2023-12-16T12:43:09+01:00 gw.example.com config 13884 - [meta sequenceId="1"] [OPNsense\MDNSRepeater\MDNSRepeater:interfaces] Option not in list.{lan}
<147>1 2023-12-16T12:43:09+01:00 gw.example.com config 13884 - [meta sequenceId="2"] Model OPNsense\MDNSRepeater\MDNSRepeater can't be saved, skip ( OPNsense\Phalcon\Filter\Validation\Exception: [OPNsense\MDNSRepeater\MDNSRepeater:interfaces] Option not in list.{lan}
<147>1 2023-12-16T12:43:09+01:00 gw.example.com config 13884 - [meta sequenceId="3"]  in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:602
<147>1 2023-12-16T12:43:09+01:00 gw.example.com config 13884 - [meta sequenceId="4"] Stack trace:
<147>1 2023-12-16T12:43:09+01:00 gw.example.com config 13884 - [meta sequenceId="5"] #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(727): OPNsense\Base\BaseModel->serializeToConfig()
<147>1 2023-12-16T12:43:09+01:00 gw.example.com config 13884 - [meta sequenceId="6"] #1 /usr/local/opnsense/mvc/script/run_migrations.php(54): OPNsense\Base\BaseModel->runMigrations()
<147>1 2023-12-16T12:43:09+01:00 gw.example.com config 13884 - [meta sequenceId="7"] #2 {main} )
<45>1 2023-12-16T12:43:16+01:00 gw.example.com syslog-ng 27514 - [meta sequenceId="1"] Configuration reload request received, reloading configuration;
<45>1 2023-12-16T12:43:16+01:00 gw.example.com syslog-ng 27514 - [meta sequenceId="2"] Configuration reload finished;
<13>1 2023-12-16T12:43:19+01:00 gw.example.com configctl 29520 - [meta sequenceId="3"] event @ 1702726999.31 msg: Dec 16 12:43:19 gw.example.com config[63134]: config-event: new_config /conf/backup/config-1702726999.1285.xml
<13>1 2023-12-16T12:43:19+01:00 gw.example.com configctl 29520 - [meta sequenceId="4"] event @ 1702726999.31 exec: system event config_changed

```

**Screenshots**
![image](https://github.com/opnsense/core/assets/1075960/f6953464-e3d3-4c90-b4cb-37b70d88e418)

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.10_1 (amd64).

**Comment by fichtner** [comment]
Hmm that’s the integrated model default of mdns-repeater. The interface field does have this annoying draw-back since I guess you don’t have that particular “lan” interface anymore, but in this case the problem is more on the plugin side. Maybe we should opt for making interface selection optional, but only when “enable” checkbox is not set?
