### ISSUE TITLE
Captive Portal: "Allowed MAC-Address" ignored

### ISSUE THREAD

**Issue by white-rabbit07** [opnsense/core#7438]
Hi.
There's a problem with our Captive Portal and the Whitelist for the MAC-addresses. 
Since one the last update the whitelisted MAC-addresses are ignored. 
The same problem was reported [here](https://forum.opnsense.org/index.php?topic=32859.msg159241#msg159241) last year.

Another problem: 
The list -> Service: Captive Portal: Sessions is empty now but I found this error-message in the Logfiles:
`tail /var/log/configd/latest.log `

`Script action failed with Command
'/usr/local/opnsense/scripts/OPNsense/CaptivePortal/listClients.py /zoneid '0'
/output_type 'json'' returned non-zero exit status 1. at Traceback (most recent call last):   
File "/usr/local/opnsense/service/modules/actions/script_output.py", line 44, in execute
subprocess.check_call(script_command, env=self.config_environment, shell=True,   
File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call     
raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError:
Command '/usr/local/opnsense/scripts/OPNsense/CaptivePortal/listClients.py /zoneid '0'
/output_type 'json'' returned non-zero exit status 1.`
(often repeated)

Can anybody confirm this?
`
Versions: 	
OPNsense 24.1.6-amd64
FreeBSD 13.2-RELEASE-p11
OpenSSL 3.0.13
`

**Comment by white-rabbit07** [comment]
temporary solution until it is fixed:
https://forum.opnsense.org/index.php?topic=19012.0
