### ISSUE TITLE
Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /usr/local/etc/inc/rrd.inc

### ISSUE THREAD

**Issue by Zeitkind** [opnsense/core#8043]
Due to a hardware failure I have to replace one of my firewalls. 
OPNsense version still 24.1.10_8 aka 11.2, I made a fresh install from USB, set LAN and WAN so I could update to 24.1.10_8, installed the plugins I use, reboot, then tried to restore from backup.

Backup setting: no rrd, no encryption on source system
Restore settings: all (default), exclude console setting (default)
Import starts, then it switches to a (debug?) website with:

Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /usr/local/etc/inc/rrd.inc:622 Stack trace: #0 /usr/local/www/diag_backup.php(336): rrd_import() #1 {main} thrown in /usr/local/etc/inc/rrd.inc on line 622

Tried 3 times with different installations and 2 different backup-config.xml - same result. In the backup-xml the rrd part is just
```

  <rrddata>
  </rrddata>

```
i.e. no data, and rrd.inc has only 100 lines(?), so.. no idea. The import kinda succeeds, if I reboot, the system boots up with the right IP and settings, but I can't see if all data is restored. Any hints? Ideas?

**Comment by Zeitkind** [comment]
Additional info:
Just tried to import the backup to a vanilla 24.7.8. Error stays, but now

Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /usr/local/etc/inc/rrd.inc:56 Stack trace: #0 /usr/local/www/diag_backup.php(337): rrd_import() #1 {main} thrown in /usr/local/etc/inc/rrd.inc on line 56 

Looking into the code, that seems to be the part it looks for rrddata, so I tried simply removing the empty
`
  <rrddata>
  </rrddata>`

in the config.xml and now restore works without an error.
